version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - movers
    depends_on:
      - database
  database:
    image: mongo:4
    volumes:
      - mongo:/data/db
    networks:
      - movers
    ports:
      - 27017:27017
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mongo:

networks:
  movers:
